### ISSUE TITLE
render bug

### ISSUE THREAD

**Issue by yocmen** [FortAwesome/react-fontawesome#48] opened 2017-12-30 18:22 UTC
Hi, i import my fontawesome-all.js with a script tag on the head, then in my react component import the reac-fontawesome, all work grate but fails the render if i have a conditional to show different icons, in my deafult state i have the save icon, then on saving mode i have a spinning cog, (that works good) but when my saving status is false again my text button change correctly but the icon remains with the cog... 

```
<button className="btn btn-primary" disabled={myProps.working} onClick={this._handleClick}>{myProps.working ? <span><FAIcon icon="cog" className="icon-spin-3x icon-1-5x icon-middle" />&nbsp;Please wait...</span> : <span><FAIcon icon="save" className="icon-1-5x icon-middle" />&nbsp;{myProps.text ? myProps.text : 'SAVE'}</span>}</button>
``` 

default (saving status false) : save -> works
saving status true : cog -> works
default again (saving status false) : still the cog icon

maybe im missing some thing, thanks in advance.

**Comment by rheinheimer** [comment] 2018-01-10 20:36
I have the same issue, with a different icon of course. First render is correct. First re-render is correct. First re-re-render doesn't work. In my case, I'm toggling between folder and folder-open.

**Comment by robmadole** [comment] 2018-01-13 18:51
I'm trying to reproduce this: https://codesandbox.io/s/2vx611pk2j

Can anyone provide an example I can see this behavior?

**Comment by yocmen** [comment] 2018-01-13 21:16
I  tested a lot and the issue is when u use the external fontawesome-all.js on your html... if i remove it from my index.html the react component render good.

**Comment by rheinheimer** [comment] 2018-01-14 23:44
Including defer worked! Thanks @yocmen. No other issues for me related to this.

**Comment by yocmen** [comment] 2018-01-15 15:22
no problem, glad for u, in my case the defer attribute dont work, it work on the react component but i lost all my icons on my app (html)

**Comment by rheinheimer** [comment] 2018-01-15 21:37
Actually, me too now. There seems to be a fundamental conflict between using FontAwesomeIcon and using the <i> tag. Not sure why that is, but my solution is basically to convert all icons to the react component version. This should work, except for the non-React bits of my app, where I'll need to fall back on a different icon set (Blueprint js, FWIW - great icon set for data-centric apps).

**Comment by mlwilkerson** [comment] 2018-01-22 23:58
I suspect that this is related to the auto replace functionality. We have a PR in our private repo (#188). I'm turning my attention to reviewing and releasing that soon at which time I hope @yocmen and/or @rheinheimer might be willing to try out a pre-release and provide feedback.

**Comment by j-f1** [comment] 2018-01-23 00:03
Direct PR reference for those with access: FortAwesome/Font-Awesome-Prop#188

**Comment by mlwilkerson** [comment] 2018-01-23 00:07
Related to #188 in our private repo is #51 in this one.

**Comment by yocmen** [comment] 2018-01-23 02:16
i removed the 0.0.17 and add the no-no-auto branch... compile it (with no extra config) and dont work.. still the render bug.... :(

**Comment by mlwilkerson** [comment] 2018-01-23 02:24
We have a PR for the main API library that would have to be merged before you’d see any difference—if that’s in fact the cause. 

Sent from my iPhone

**Comment by yocmen** [comment] 2018-01-23 02:37
from this one? https://github.com/FortAwesome/Font-Awesome-Pro

**Comment by mlwilkerson** [comment] 2018-01-23 03:36
No, sorry.

**Comment by robmadole** [comment] 2018-01-23 05:35
OK, I've uncovered the root cause of this. @mlwilkerson this is going to take a compatibility fix in the main `fontawesome` lib. I'll try to get to this tomorrow.

**Comment by robmadole** [comment] 2018-02-15 15:14
This should be resolved now. Let us know if it's still a problem.

**Closed by robmadole** 2018-02-15 15:14 UTC

**Comment by yocmen** [comment] 2018-02-15 17:04
It works now!!!! really thanks!!!!! awesome job.
